config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :cars

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
    p "*" * 100
    p "index"
    p params
    p "*" * 100
  end

  def new
    @car = Car.new
    p "*" * 100
    p "new"
    p params
    p "*" * 100
  end

  def create
    p "*" * 100
    p "create"
    p params
    p "*" * 100
    Car.create(car_params)
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :year, :color)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cars/index.html.erb
<% @cars.each do |car| %>
    <h1><%= car.year %></h1>
    <h1><%= car.make %></h1>
    <h1><%= car.model %></h1>
    <h2><%= car.color %></h2>
    <h1>-------------------</h1>
<% end %>

app/views/cars/new.html.erb
<h1>Enter the details of your first car</h1>
<%= simple_form_for @car do |f| %>
  <%= f.input :year %>
  <%= f.input :make %>
  <%= f.input :model %>
  <%= f.input :color %>
  <br />
  <%= f.submit 'Add my car', class: 'btn btn-danger' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>This is Quiz #1</h1>
<h2>Look at me, I'm coding a webpage!</h2>

<h1>The date and time is now...

<%= DateTime.now.strftime "%A, %m/%d/%Y %H:%M %p %Z" %>

</h1>

<br />
<h2> Look at a list of some peoples' first car...</h2>
<button><%= link_to '<button type="button">Others\' First Car</button>'.html_safe, cars_path %></button>
<button><%= link_to '<button type="button">Add my Car</button'.html_safe, new_car_path %> </button>